#!/run/current-system/sw/bin/bash
#
message="Auto-Submission"
tags=""
files='*'

#find . -regex '.*\.\(h\|c\)' -exec clang-format -style=file -i {} \;
# find . \( -name \*.cc -o -name \*.hh \) -exec clang-format -style=file -i {} \;
if [[ "$OSTYPE" == "darwin"* ]]; then
    find . '(' -name \*.c -o -name \*.h ')' -a -exec clang-format -style=file -i {} \;
else
    clang-format-epita
fi
rm $(git rev-parse --show-toplevel)/.git/index.lock 2> /dev/null
until [ $# -eq 0 ]; do

    if [ "$1" = "-m" ] || [ "$1" = "--message" ];then
        message=$2
        shift 2
    fi
    if [ "$1" = "-t" ] || [ "$1" = "--tags" ]; then
        [ $2 != "" ] && tags=$2 && shift 2
    fi
done
git add .
git status
git commit -m "$message"
if [ "$tags" = "" ]; then
    git push
else
    if [[ "$tags" == *"*"* ]]; then
        tag_prefix=$(echo "$tags" | sed 's/\*//')

        last_tag=$(git tag --list "$tag_prefix*" | sort -V | tail -n 1)

        if [ -z "$last_tag" ]; then
            new_tag="${tag_prefix}1"
        else
            last_number=$(echo "$last_tag" | sed "s/^$tag_prefix//")
            new_number=$((last_number + 1))
            new_tag="${tag_prefix}${new_number}"
        fi
    else
        new_tag="$tags"
    fi

    git tag -a "$new_tag" -m "$new_tag"
    git push --follow-tags
fi
exit 0
