#!/usr/bin/env python
import sys
import re
MAX_LINE = 40
def count_paren(line):
    return line.count('{') - line.count('}');

def is_line(line):
    l = line.strip()
    if (l == ''):
        return False
    if (l == '{'):
        return False
    if (l == '}'):
        return False
    return True

file1 = open(sys.argv[1], 'r')
Lines = file1.readlines()

in_func = False
line_count = 0
paren_balance = 0
current = ""

cur_line = 0

for line in Lines:
    cur_line += 1
    if (re.match(r"^([a-z_]+ +)+\*?[a-z_0-9]+\(.*$", line)):
        current = line.strip()
        paren_balance = paren_balance + count_paren(line)
        in_func = True
    elif (in_func):
        if is_line(line):
            line_count += 1
        paren_balance = paren_balance + count_paren(line)
        if (paren_balance == 0):
            if line_count > MAX_LINE:
                print("Expected {} got {}: ({}) {}".format(MAX_LINE,line_count, cur_line, current))
            in_func = False
            line_count = 0
            continue
